apiVersion: v1
kind: Service
metadata:
  name: java-jsp-webapp-service
  labels:
    app: java-jsp-webapp
spec:
  type: LoadBalancer
  selector:
    app: java-jsp-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
